### ISSUE TITLE
Cut control labels with "..." instead of "line breaking" them

### ISSUE THREAD

**Issue by SigurdJanson** [SigurdJanson/DSADiceApp#67]
Labels have the class "control-label".

try this CSS:
```CSS
.control-label {
  text-overflow: ellipsis;
  /* Required for text-overflow to do anything */
  white-space: nowrap;
  overflow: hidden;
}
```
See https://css-tricks.com/almanac/properties/t/text-overflow/
